### ISSUE TITLE
not an issue, a thank you

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [Aravindjeev/camunda-helm#1]
Having worked all day on many other components than camunda, A thank you for yours :  it is the first today, that works with no error, with a clear, neat process.

```bash
~/atelier-helm$ git clone https://github.com/Aravindjeev/camunda-helm
Cloning into 'camunda-helm'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 15 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.
~/atelier-helm$ helm install jbl-camunda camunda-helm/
NAME: jbl-camunda
LAST DEPLOYED: Mon Jun 29 00:22:52 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
~/atelier-helm$ kubectl get all,secrets,confgimaps |grep camunda
error: the server doesn't have a resource type "confgimaps"
~/atelier-helm$ kubectl get all,secrets,configmaps |grep camunda
pod/jbl-camunda-camunda-776459db4f-sd766                      1/1     Running       0          60s
service/jbl-camunda-camunda                            NodePort    10.100.161.51    <none>        80:31676/TCP                 60s
deployment.apps/jbl-camunda-camunda                      1/1     1            1           60s
replicaset.apps/jbl-camunda-camunda-776459db4f                      1         1         1       60s
secret/sh.helm.release.v1.jbl-camunda.v1                             helm.sh/release.v1                    1      60s
```
And there is a replicaSet.

Did you consider shifting from NodePort, to LoadBalancer Service Type ? I believe this will require a `StatefulSet`.

I'll be glad to contribute your repo, if you consider this evolution.

**Comment by Aravindjeev** [comment]
Hey @Jean-Baptiste-Lasselle,
I haven't tried with LoadBalancer, since i used this for a On-prem deployment. We might not need a statefulset here i guess. We can modify the ServiceType to LoadBalancer directly and it should probably work.
You're Welcome to Contribute

**Comment by Jean-Baptiste-Lasselle** [comment]
> You're Welcome to Contribute

So I will in the next weeks, thank you for your suggestion on the not required `StatefulSet`, i will test this with interest (I really had exepected to find a stateful set, for an execution engine, how can it keep the state of a BPMN execution ..? That's really interesting...)
